<?php $this->load->view('front/header/header'); ?> 
<header>
	<div class="container">
		<div class="row">
			<div class="col-12" style="height: 22px;"></div>
			<div class="col-12 d-flex justify-content-between align-items-center hedMain">
				<div class="leftRight"><button onclick="location.href = '<?php echo base_url();?>index.php/Cust_home/settings';"><img src="<?php echo base_url(); ?>assets/img/back-icon.svg"></button></div>
				<div><h1>Terms & Conditions</h1></div>
				<div class="leftRight">&nbsp;</div>
			</div>
		</div>
	</div>
</header>

<main class="padTop padBottom">
	<div class="container">
		<div class="row">
			<div class="col-12 termsPrivacyWrapper">
				<p>These Terms and Conditions of Use (the “Terms”) are a legal agreement between You (“You”, “Your”, etc.) and Us (“We”, “Our” or “Us”) and govern Your use of Our services, including mobile applications, websites, software, hardware, and other products and services (collectively, the “Services”). If agreeing on behalf of a company, You represent that You are authorized to bind such business and such business accepts these terms. By using the App You agree to these Terms and any policies referenced within (“Policies”). You should read all of our Terms carefully. PLEASE READ THESE TERMS AND CONDITIONS OF USE (“TERMS OF USE”) BEFORE USING THE APP. BY CLICKING BELOW AND/OR YOUR USE OF THE APP CONSTITUTES AN AGREEMENT WITH THE TERMS AND USE. BY CLICKING BELOW AND/OR USING THE APP, YOU HEREBY REPRESENT, WARRANT, UNDERSTAND, AGREE TO AND ACCEPT ALL TERMS AND CONDITIONS CONTAINED HEREIN. IF YOU OBJECT TO ANYTHING IN THESE TERMS OF USE OR THE OUR PRIVACY POLICY, DO NOT USE THE APP.</p>
                <ul class="termsMain">
					<h3>Acceptance of Terms and Conditions of Use</h3>
					<li>These Terms of Use are effective as of November 1, 2022 (the “Effective Date”) and constitute an electronic contract that sets forth the legally binding terms of Your use of the App and the Service. These Terms of Use may be modified by Us from time to time, with such modifications to be effective upon posting by Us on the App. These Terms of Use include the Our Privacy Policy. By accessing and/or using the App, You accept these Terms of Use and agree to the Terms, conditions and notices contained or referenced herein. In addition, by using the App, You consent to have these Terms of Use provided to You in electronic form.</li>
					<h3>Account</h3>
					<li>You must open an account (Your “Account”) with Us to use the App. To do so, You must create a unique user identification and password (the “Login Credentials”). You agree that You are solely responsible for maintaining the confidentiality of and protecting against unauthorized use of Your Login Credentials, and You agree to accept responsibility for all activities that may occur using Your Login Credentials. You agree to notify Us immediately if You believe that any of Your Login Credentials have been or may be used without Your permission so that appropriate action may be taken. We are not responsible for any loss or damage caused by, or expense incurred by You, as a result of Your failure to safeguard Your Login Credentials. We may terminate Your Account at any time at Our sole discretion and with no liability to You. We may also prohibit certain Users from re-registering with the App, at Our sole discretion. Your Account is for Your sole, personal use, and You may not authorize others to use Your Account, and You may not assign or otherwise transfer Your Account to any other person or entity.</li>
					<li>If you wish to permanently delete your account, you will need to contact us through our customer care email and we will delete your account and inform you accordingly. Once your account is deleted you will not have access to the App all pending accrued points will expire and will not be available for use.</li>
					<h3>Transactions and Product Availability</h3>
					<li> You may be able to use the App and/or the Services to order and/or pay for food from restaurants or other food service provider in your area. To be able to order and pay for such food or services, you must supply certain information relevant to your transaction, including, without limitation, your credit or debit card number, the expiration date of your credit or debit card, the name on your credit or debit card, and/or your billing address. You may also be asked to supply delivery information. YOU REPRESENT AND WARRANT THAT YOU HAVE THE LEGAL RIGHT TO USE ANY CREDIT OR DEBIT CARD OR OTHER PAYMENT METHOD UTILIZED IN CONNECTION WITH ANY TRANSACTION. By submitting such information, you grant Us and/or the restaurant from which you are ordering food and/or any required third parties the right to provide and transmit such information for purposes of facilitating the completion of transactions initiated by you or on your behalf. Verification of information may be required prior to the acknowledgment or completion of any transaction. You agree to pay all charges incurred by you, on your behalf, or by your Account through the App and Services, at the price in effect when such charges are incurred. You are solely responsible for any taxes applicable to your transaction. ANY PRODUCTS OR SERVICES DESCRIBED THROUGH THE SERVICES ARE OFFERED ONLY IN JURISDICTIONS WHERE THEY MAY BE LEGALLY OFFERED FOR SALE. THE INFORMATION PROVIDED THROUGH THE SERVICES IS NOT AN OFFER OR SOLICITATION BY ANYONE IN ANY JURISDICTION IN WHICH AN OFFER OR SOLICITATION CANNOT LEGALLY BE MADE, OR ANY PERSON TO WHOM IT IS UNLAWFUL TO MAKE A SOLICITATION. You understand and agree that you are charged at the time you place your order for food or services. You further understand and agree that the transaction for the purchase of food or services is final and complete at the time you are charged. Once an order is placed, changes cannot be made to the order.
					</li>
					<h3>Covenants, Representations and Warranties</h3>
					<li> You represent and warrant to Us that each of the following are true and correct in all material respects:
						<ul class="trems">
							<li> You are eighteen (18) years of age or older. If You do not meet the above age requirements, You must not attempt to register to use the App.</li>
							<li>You are not a Competitor (as hereinafter defined) of Poppin Pay, LLC (the “Software Provider”) and are not using the App for reasons that are in competition with Software Provider. As used herein, a “Competitor” means any company or individual that is in the business of developing software.</li>
							<li>All information provided by You through the App is and will remain true and correct in all material respects so long as You are using the App.</li>
							<li>You are authorized and have all requisite legal and corporate power to enter into these Terms of Use and any ancillary agreements, and to carry out and perform its other obligations under the terms of these Terms of Use.</li>
							<li>No consent of any third party (including, but not limited to, a party to a material contract to which You are a party) is required for You, to enter into these Terms of Use or fulfill the obligations contemplated hereby.</li>
						</ul>
					</li>
					<h3>Compatibility</h3>
					<li>We do not warrant that the App will be compatible with Your mobile device or carrier. Your use of the App may be subject to the terms of Your agreements with Your mobile device manufacturer or Your carrier. You may not use a modified device to use the App if the modification is contrary to the manufacturer’s software or hardware guidelines, including disabling hardware or software controls (sometimes referred to as “jail broken”).</li>
					
					<h3>Termination</h3>
					<li>We may terminate Your access to the App, for any reason and at any time, with or without prior notice. It is Our policy to terminate users who violate these Terms of Use, as deemed appropriate in Our sole discretion, but We may also terminate access without cause or notice. We may terminate Your access to the App if You do not use Your Account for an extended period of time, as determined by Us from time to time in its sole discretion. You agree that We are not liable to You or any third party for any termination of Your access to the App. You may terminate Your Account at any time by simply deleting Your Account.</li>
					
					<h3>Prohibited Conduct</h3>
					<li>You shall not disturb or interfere with the operation of the App in any manner, including, but not limited to, imposing an unreasonable or disproportionate burden on the network, software or hardware infrastructure of the App. By accessing the App, You shall abide by the following standards of conduct. You shall not, and will not authorize or facilitate any attempt by another person, to use the App to: (a) infringe upon the Our or the Software Provider’s copyright, trademark or trade secret; (b) take any action violative of the Children’s Online Privacy Protection Act of 1998 (COPPA); (c) introduce viruses, worms, Trojan horses and/or harmful code into the App; (d) obtain unauthorized access to any computer system or Confidential Information through the App; (e) transfer Your Account and/or Login Credentials to another party without Our consent; (f) harvest or otherwise collect information about other users of the App without their consent; (g) violate any federal, state, local, or international law or regulation; or (h) engage in or encourage conduct that would constitute a criminal or civil offense.</li>
					<h3>Privacy</h3>
					<li>We will only use the information You provide through the App in accordance with Our Privacy Policy. For more information, see our full Privacy Policy, the terms of which are incorporated herein. By agreeing to these Terms of Use, You are consenting to receive certain communications from Us. If You no longer want to receive such communications, You may unsubscribe.</li>
					
					<h3>Links to External Sites</h3>
					<li>Links from the App to external sites (if any) or inclusion of advertisements do not constitute an endorsement by Us of such sites or the content, products, advertising and other materials presented on such sites or of the products and services that are the subject of such advertisements, but are for users’ reference and convenience. Your access is at Your own risk. It is Your responsibility to evaluate the content and usefulness of the information obtained from other sites. We do not control such sites, and are not responsible for their content. You further acknowledge that use of any site controlled, owned or operated by third parties is governed by the terms and conditions of use for those sites, and not by Our Terms and Conditions and Privacy Policy. We expressly disclaim any liability derived from the use and/or viewing of links that may appear on the App. You hereby agree to hold Us and Software Provider harmless from any liability that may result from the use of links that may appear on the App.</li>
					
					<h3>Intellectual Property Rights</h3>
					<li>Restrictions :
						<ul class="trems">
							<li>Site Content. All of the content on the App, including without limitation the images, graphics, information, text, data, links, as well as the underlying software, networks and systems that support the App and other material accessible through the App, whether created by Us, provided by You or provided by a third party, for display on the App or through the App (collectively, the “Content”) is owned by or under license to Us and is protected by applicable trademark, copyright, or other rights. You are granted a non-transferable, non-sublicensable, non-exclusive, revocable, and limited right to access and use the App and its Content solely for Your personal use, subject to these Terms of Use. The Content may contain typographical errors, other inadvertent errors, or inaccuracies. We reserve the right to make changes to document names and content, descriptions or specification, or other information, without obligation to issue any notice of such changes. You may only use the Content for internal informational purposes in compliance with all laws and regulations that apply to You. You may not reproduce or transmit any part of the App or its Content in any form, by any means, electronic or mechanical, including photocopying and recording for any other purpose. You may not modify, alter, or prepare derivative works or the App and/or based on the Content, or distribute copies of or publicly perform or display the Content. You may not remove copyright, trademark, and other proprietary notices from the Content.</li>
							<li>Ownership of Content. Unless otherwise noted, all Content contained on the App is the property of Us, the Software Developer, and/or Our licensors, and is protected from unauthorized copying and dissemination by United States copyright law, trademark law, international conventions and other intellectual property laws. Product names are trademarks or registered trademarks of their respective owners. We do not claim ownership of any Content submitted by Users. By submitting such Content, however, You hereby grant Us and Software Developer a world-wide, royalty-free, perpetual, irrevocable, non-exclusive license to use, distribute, reproduce, modify, adapt, create derivative works from, publicly perform and/or display such Content. This license shall remain in effect until We delete the Content from Our systems.</li>
						</ul>
					</li>
					<h3>COPPA Compliance</h3>
					<li>You should monitor children’s use of the Internet. The App is intended for people eighteen (18) years of age or older. We will not knowingly collect any information from children under thirteen (13) years of age. You must identify Your age during the registration process. We take the Children’s Online Privacy Protection Act of 1998 (COPPA) as well as all FTC regulations very seriously. That being said, We do not assume any responsibility for any misrepresentations regarding Your age or parental consent when using the App. Should We determine that You provided any false information to Us when using the App, Your Account will be terminated immediately.</li>
					
					<h3>Disclaimer of Warranties</h3>
					<li>The information and materials contained in the App, including text, graphics, information, links, content, accounts and/or other items are provided “as is” and “as available”. NEITHER WE NOR SOFTWARE DEVELOPER WARRANT THE ACCURACY, ADEQUACY OR COMPLETENESS OF THIS INFORMATION AND/OR MATERIALS AND EXPRESSLY DISCLAIM LIABILITY FOR ERRORS OR OMISSIONS IN THIS INFORMATION AND MATERIALS. NO WARRANTY OF ANY KIND, IMPLIED, EXPRESSED OR STATUTORY INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF NON-INFRINGEMENT OF THIRD PARTY RIGHTS, TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND FREEDOM FROM COMPUTER VIRUS, IS GIVEN IN CONJUNCTION WITH THE INFORMATION AND MATERIALS. NEITHER WE NOR SOFTWARE DEVELOPER WARRANT THAT YOUR USE OF THE APP WILL BE SECURE, UNINTERRUPTED, ALWAYS AVAILABLE, ERROR-FREE OR WILL MEET YOUR REQUIREMENTS, OR THAT ANY DEFECTS IN THE APP WILL BE CORRECTED. WE AND SOFTWARE DEVELOPER DISCLAIM LIABILITY FOR, AND NO WARRANTY IS MADE WITH RESPECT TO, THE CONNECTIVITY AND AVAILABILITY OF THE APP.</li>
					<h3>Third Party Content</h3>
					<li>Opinions, advice, statements, offers, or other information or content made available through the App, but not directly by Us, are those of their respective authors, and should not necessarily be relied upon. Such authors are solely responsible for such content. WE DO NOT: (i) GUARANTEE THE ACCURACY, COMPLETENESS OR USEFULNESS OF ANY INFORMATION PROVIDED ON THE APP, OR (ii) ADOPT, ENDORSE OR ACCEPT RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY OPINION, ADVICE, OR STATEMENT MADE BY ANY PARTY OTHER THAN US. UNDER NO CIRCUMSTANCES WILL WE BE RESPONSIBLE FOR ANY LOSS OR DAMAGE RESULTING FROM ANYONE’S RELIANCE ON INFORMATION OR OTHER CONTENT POSTED ON THE APP OR TRANSMITTED TO OR BY ANY USERS.</li>
					<h3>Limitation of Liability</h3>
					<li>In no event will We or Software Developer be liable for any indirect, special, incidental, or consequential damages, losses or expenses arising out of or relating to the use or inability to use the App, including without limitation damages related to any information received from the App, removal of content from the App, including Account information, termination of Your Account or ability to access the App, failure of performance, error, omission, interruption, defect, delay in operation or transmission, computer virus or line or system failure, even if We or Software Developer, as the case may be, are advised of the possibility of such damages, losses or expenses. UNDER NO CIRCUMSTANCES WILL OUR OR SOFTWARE DEVELOPER’S AGGREGATE LIABILITY, IN ANY FORM OF ACTION WHATSOEVER IN CONNECTION WITH THESE TERMS OF USE OR THE USE OF THE APP, EXCEED THE PRICE PAID BY YOU FOR YOUR ACCOUNT, OR, IF YOU HAVE NOT PAID US FOR THE USE OF ANY SERVICES, THE AMOUNT OF $25.00 OR ITS EQUIVALENT
					<br><br>JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</li>
					<h3>Indemnification</h3>
					<li>By clicking below and/or using the App You are agreeing to the terms of these Terms of Use, and You agree to indemnify, defend and hold harmless Us and Software Developer from and against any and all claims, losses, expenses or demands of liability, including attorneys’ fees and costs incurred by Us and/or Software Developer in connection with any claim by a third party (including an intellectual property claim) arising out of: (i) the Content You submit through the App; (ii) Your use of the App in violation of these Terms of Use or in violation of any applicable law; and (iii) any services provided by You. You further agree that You will cooperate as reasonably required in the defense of such claims.</li>
					<h3>Miscellaneous</h3>
					<li>Nothing in these Terms of Use shall be construed as making either party the partner, joint venturer, agent, legal representative, employer, contractor or employee of the other. Nor is any Customer or You a partner, joint venturer, agent, legal representative, employer, contractor or employee of Us. It is understood and agreed that Software Developer is an intended third-party beneficiary to these Terms of Use; provided, however, that in no event is Software Developer assuming any obligations of Us to You. Neither party shall have, or hold itself out to any third party as having, any authority to make any statements, representations or commitments of any kind, or to take any action, that shall be binding on the other, except as provided for herein or authorized in writing by the party to be bound. If suit is brought by any party to these Terms of Use to enforce the terms hereof, to collect any money due, or to obtain any money damages or equitable relief for breach, the prevailing party shall be entitled to recover, in addition to any other available remedy, reimbursement for reasonable attorneys’ fees, court costs, costs of investigation, and other related expenses. If any part of these Terms of Use is held to be unlawful, void, or unenforceable, that part will be deemed severable and shall not affect the validity and enforceability of the remaining provisions. You expressly agree that any dispute related to or arising out of the use of the App and/or the Network shall be governed by the laws of the State of Georgia, without regard to its conflict of law provisions, and You expressly agree and consent to the exclusive jurisdiction and venue of the state and federal courts of the State of Kenya  , for the resolution of any such dispute. The failure of Us to enforce any right or provision of these Terms of Use will not constitute a waiver of future enforcement of that right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Us. Except as expressly set forth in these Terms of Use, the exercise by either party of any of its remedies under these Terms of Use will be without prejudice to its other remedies under these Terms of Use or otherwise. All of the provisions of these Terms of Use shall be binding upon and inure to the benefit of the parties hereto and their respective heirs, if any, successors, and assigns.</li>
				</ul>
			</div>
		</div>
	</div>
</main>
<?php $this->load->view('front/header/footer');  ?>		